### ISSUE TITLE
Teclado error

### ISSUE THREAD

**Issue by IsaacExolivil** [JayAnthony2225/Books-Mark-App#1]
Hola buenas tardes marco revisando tu código, me parece muy bien, tus vistas no las encuentro cargadas, lo unico que veo el error de "keyWindows" quedo obsoleto, en iOS 13 te dejo el link como solucionarlo. https://qastack.mx/programming/57134259/how-to-resolve-keywindow-was-deprecated-in-ios-13-0
En cuanto al diseño me muy bonito, y fluido, solo me dio mucho trabajo a la hora de poner mi correo en el simulador, pues la pantalla no es scroll, otra cosa que me fije algunos títulos son largos y con la imagen del descuento se pierde el nombre, o el nombre cuando le doy scroll se pierde 
Anexo fotos.
En son todo, tanto la lógica, la estructura del proyecto todo ordenado.
Excelente trabajo (y)
<img width="221" alt="Captura de Pantalla 2022-01-31 a la(s) 13 57 36" src="https://user-images.githubusercontent.com/90442755/151864769-d7a5f0f8-dd90-4377-95d2-3ff5ba4f829b.png">
<img width="231" alt="Captura de Pantalla 2022-01-31 a la(s) 13 58 22" src="https://user-images.githubusercontent.com/90442755/151864818-e1d2f3e1-79bf-4f88-a365-5cec398e1b63.png">

**Comment by JayAnthony2225** [comment]
Hola Isac buenas tardes,
Muchas gracias por el feedback , me pondre a corregirlo de manera inmediata , es mi primer proyecto y significa mucho para mi los buenos comentarios de un pro como tu, seguire mejorando esas areas de oportunidad , mil gracias.
Nos vemos en la sesion de hoy.
que tengas un excelente dia !

**Comment by JayAnthony2225** [comment]
Hola Isac, buenas tardes,
para darle  el seguimiento a este punto , ya se actualizo el "KeyWindows" y se actualizo el titulo dinamico de las categorias en la tableView.
me sirvio de mucho la informacion que me proporcionaste, mil gracias.
Espero te encuentres de maravilla.
Anexo imagen con evidencia. 
saludos.
Marco A. Cruz 


<img width="873" alt="Screen Shot 2022-02-15 at 3 49 34 PM" src="https://user-images.githubusercontent.com/89218826/154155256-ece7a93c-7af3-4f04-8dac-c4495839d922.png">
